export const GET_REDDIT_POST_START = "GET_REDDIT_POST_START"
export const GET_REDDIT_POST_SUCCESS = "GET_REDDIT_POST_SUCCESS"
export const GET_REDDIT_POST_ERROR = "GET_REDDIT_POST_ERROR"

export const ORDER_REDDIT_POST_START = "ORDER_REDDIT_POST_START"
export const ORDER_REDDIT_POST_SUCCESS = "ORDER_REDDIT_POST_SUCCESS"